= Liquid Crystal Library for Arduboy =

Have put together a modified version of the Arduino **LiquidCrystal** library, which allows the Arduboy to be used as a full-featured 16x2 character display!

The two rows of 16 characters are rendered directly to the screen, and fill up the top half (128x32). You can watch the demo using ProjectABE:

https://felipemanga.github.io/ProjectABE/?url=https://raw.githubusercontent.com/uXeBoy/ArduboyLiquidCrystal/master/ArduboyLiquidCrystal.ino.hex

Used a nice big 8x16 font from here:

http://www.rinkydinkelectronics.com/r_fonts.php

And adapted a couple of the functions from here:

https://github.com/dylangageot/LCDSim

Was able to run all of the **LiquidCrystal** example sketches with just a few edits - have not implemented custom characters yet, happy to leave it at this for now!

== License ==

Copyright (C) 2006-2008 Hans-Christoph Steiner. All rights reserved.
Copyright (c) 2010 Arduino LLC. All right reserved.

This library is free software; you can redistribute it and/or
modify it under the terms of the GNU Lesser General Public
License as published by the Free Software Foundation; either
version 2.1 of the License, or (at your option) any later version.

This library is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public
License along with this library; if not, write to the Free Software
Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
